stemmer.lo: /Users/camilobravo/Dropbox/Trab/2013/Thoughts/thoughts/sites/all/modules/languageutil/php-stemmer-0.7.0/stemmer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/camilobravo/Dropbox/Trab/2013/Thoughts/thoughts/sites/all/modules/languageutil/php-stemmer-0.7.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/camilobravo/Dropbox/Trab/2013/Thoughts/thoughts/sites/all/modules/languageutil/php-stemmer-0.7.0/stemmer.c -o stemmer.lo 
$(phplibdir)/stemmer.la: ./stemmer.la
	$(LIBTOOL) --mode=install cp ./stemmer.la $(phplibdir)

./stemmer.la: $(shared_objects_stemmer) $(STEMMER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_stemmer) $(STEMMER_SHARED_LIBADD)

