<?php

const THOUGHT_SEARCH_CRON_RUNTIME = 20; //seconds the cron is allowed to run (not a hard limit)
module_load_include('module', 'languageutil');
include_once 'thought_search.admin.inc';
include_once 'thought_search.node.inc';

/**
 * Implements hook_cron().
 */
function thought_search_cron() {
  $initial_time = time();

  do {
    //get some unprocessed nodes
    $query = db_select('node', 'n');
    $query->leftJoin('thought_processed_nodes', 'pn', 'n.nid = pn.nid');
    $query
      ->fields('n', array('nid'))
      ->isNull('pn.nid')
      ->condition('n.type', 'thought')
      ->range(0, 5);

    $to_update = $query->execute()->fetchCol();
    if (!count($to_update))
      break;
    
    foreach ($to_update as $nid) {
      _thought_search_store_node_data(node_load($nid));
      
      //are we out of time?
      if (time() - $initial_time >= THOUGHT_SEARCH_CRON_RUNTIME)
        break;
    }
  }
  while (time() - $initial_time < THOUGHT_SEARCH_CRON_RUNTIME);
}

/**
 * Implements hook_menu().
 */
function thought_search_menu() {
  return array(
    'admin/config/search/thought' => array(
      'title' => 'Thought search',
      'description' => 'Configuration for Thought specific search',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('thought_search_settings_form'),
      'access callback' => TRUE,
      'file' => 'thought_search.admin.inc',
    )
  );
}

/**
 * Implements hook_theme().
 */
function thought_search_theme() {
  return array(
    'thought_search_settings' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}
